export const PKG_PREFIX = '@element-plus'
export const PKG_NAME = 'element-plus-x'
export const PKG_CAMELCASE_NAME = 'ElementPlusX'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusLocale'
export const PKG_BRAND_NAME = 'Element Plus'
